language: erlang
otp_release:
  # Not available on Travis CI: 19.1, 19.2 and 20.2
  - 19.0
  - 19.3
  - 20.0
  - 20.1.7
  - 20.3.8.22
  - 21.0.9
  - 21.1.4
  - 21.2.7
  - 21.3.8.1
  - 22.0.7
  - 22.1.8.1
  - 22.2.8
  - 22.3.4
  - 23.0.2

env:
  - TEST=1

before_script:
    - kerl list installations
    - "gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&"

before_install:
  - sudo pip install -q httpbin
  - sudo pip install -q gunicorn

script:
  - ./support/rebar3 eunit
  - ./support/rebar3 dialyzer

cache:
  directories:
    - $HOME/.cache/rebar3
